### PR TITLE
Fix for #615: Use ValueInstantiators to rename creator properties so they match property definitions

### LINKED ISSUE #615: Deserialization of Xml with `@JacksonXmlText` fails
This is a reproduction of #198. It was mentioned opening a new issue is preferred.

The issue is, that `@JacksonXmlText` seems to work as intended for serialization, but not for deserialization.

Hence, my reproduction of the original issue with 2.15.4:

I have the following models and tests:

```java
@JacksonXmlRootElement(localName = "ITEMROOT")
public record ItemRoot(
        @JsonProperty("Item") @JacksonXmlElementWrapper(useWrapping = false)
                List<Item> item) {
    
	public record Item(
            @JsonProperty("name") @JacksonXmlProperty(isAttribute = true) String name,
            @JacksonXmlText String value) {

        @JsonCreator
        public Item(final Map<String, String> item) {
            this(item.get("name"), item.get(""));
        }
    }
}

class Tests {

    @Test
    void testDeserializeItemRoot() throws JsonProcessingException {
        final var xmlMapper = new XmlMapper().registerModule(new ParanamerModule());
        final var itemRoot =
                new ItemRoot(
                        List.of(
                                new ItemRoot.Item("name1", "value1"),
                                new ItemRoot.Item("name2", "value2")));

        final var itemRootSerialized =
                xmlMapper.writerWithDefaultPrettyPrinter().writeValueAsString(itemRoot);

        final var itemRootXml =
                """
                <ITEMROOT>
                  <Item name="name1">value1</Item>
                  <Item name="name2">value2</Item>
                </ITEMROOT>
                """;
        assertEquals(itemRootXml, itemRootSerialized);

        final var itemRootDeserialized = xmlMapper.readValue(itemRootXml, ItemRoot.class);
        assertEquals(itemRoot, itemRootDeserialized);
    }
}
```

First, I serialize the model to verify what I actually want to deserialize is correct and then I serialize the XML again.

The tests pass because of `@JsonCreator` in `Item`. Without the annotation, I get the following error on the `xmlMapper.readValue()`:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid definition for property '' (of type `ch.sample.model.ItemRoot$Item`): Could not find creator property with name '' (known Creator properties: [name, value])
 at [Source: (StringReader); line: 1, column: 1]
```

### PR DESCRIPTION
**Pull request by mcvayc**
Hi,

This PR was intended to fix #615 but in the process tests for #149, #517, #735, #795 in the `tofix` package started passing as well.  I've listed all the issues for which test are now passing in the commits, but still need to verify for those that the entire issue is fixed. 

The initial solution was co-written by Claude Code and me.  After collaboratively creating a fix, I subsequently read through the code and edited it for quality and consistency.  I believe the solution is now in decent shape, at least for #615.

Please let me know what you think.  I'm happy to make further edits.

### CODE REVIEW

File: src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+                if (!_cfgNameForTextValue.equals(propName)) {
+                    creatorProps[i] = prop.withSimpleName(_cfgNameForTextValue);
+                }
+                continue;
+            }
+
+            // Second check: rename map from property definitions
+            String newName = renames.get(propName);
+            if (newName != null && !newName.equals(propName)) {
+                creatorProps[i] = prop.withSimpleName(newName);
```
Comment (mcvayc) [inline src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java]: Other than directly editing the array items, is there a better way to update the creator properties of the instantiator?  I didn't see a setter.

File: src/test/java/tools/jackson/dataformat/xml/tofix/XmlTextViaCreator306Test.java [hunk 2]
```diff
@@ -114,15 +98,4 @@ public void testIssue306NoCtor() throws Exception
         RootWithoutConstructor rootNoCtor = MAPPER.readValue(XML, RootWithoutConstructor.class);
         assertNotNull(rootNoCtor);
     }
-
-    // [dataformat-xml#423]
-    @JacksonTestFailureExpected
-    @Test
-    public void testXmlTextViaCtor423() throws Exception
```
Comment (mcvayc) [inline src/test/java/tools/jackson/dataformat/xml/tofix/XmlTextViaCreator306Test.java:121]: This test started passing so I split it out so it could be removed from the `tofix` package.

Comment (mcvayc) [reply src/test/java/tools/jackson/dataformat/xml/tofix/XmlTextViaCreator306Test.java:121]: The test now resides in `src/test/java/tools/jackson/dataformat/xml/deser/XmlTextViaCtor423Test.java`

**Comment by mcvayc** [comment]
I see the build errors, let me take a look.

**Comment by mcvayc** [comment]
Sorry about that. I somehow missed adding a module file to the commit.

I've rebased and confirmed that everything is passing on my end.
```
[INFO] --- jacoco:0.8.14:report (report) @ jackson-dataformat-xml ---
[INFO] Loading execution data file C:\Users\chips\Documents\GitHub\mcvayc\jackson-dataformat-xml\target\jacoco.exec
[INFO] Analyzed bundle 'Jackson-dataformat-XML' with 53 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.826 s
[INFO] Finished at: 2026-03-15T18:36:53-04:00
[INFO] ------------------------------------------------------------------------
```

File: src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java]: That does seem dangerous. Ideally would not tweak internal data structures nor have setters but create new instances.

I'll have to think about this one.

**Comment by mcvayc** [comment]
Additionally, since the rebase it looks like test #795 now also passes so I've also moved that one out of `tofix`.

File: src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+    private Map<String, String> _findPropertyRenames(DeserializationConfig config,
+            BeanDescription.Supplier beanDescRef)
+    {
+        final AnnotationIntrospector intr = config.getAnnotationIntrospector();
+        Map<String, String> renames = Collections.emptyMap();
+
+        for (BeanPropertyDefinition propDef : beanDescRef.get().findProperties()) {
+            AnnotatedMember member = propDef.getPrimaryMember();
+            if (member == null) {
+                continue;
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java]: Should never happen (error if it does) -- just remove the check?

File: src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+            }
+            final String origName = propDef.getName();
+
+            // Check @JacksonXmlText
+            Boolean isText = AnnotationUtil.findIsTextAnnotation(config, intr, member);
+            if (isText != null && isText.booleanValue()) {
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java]: -> if (Boolean.TRUE.equals(isText))

File: src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java [hunk 5]
```diff
@@ -29,6 +29,16 @@ public class JacksonXmlAnnotationIntrospector
...
 
+    /**
+     * Marker PropertyName used for {@code @JacksonXmlText} creator parameters.
+     * Must be non-empty so {@code PotentialCreator} recognizes the parameter as named.
+     * {@link tools.jackson.dataformat.xml.deser.XmlValueInstantiators} will later rename this to the actual text element
+     * name (empty string by default).
+     *
+     * @since 3.2
+     */
+    private final static PropertyName _XML_TEXT_NAME = PropertyName.construct("#xml.text");
```
Comment (cowtowncoder) [inline src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java]: Since there is possible name conflict with actual properties, it's good that this is NOT a valid XML name. I think leading "#" guarantees that?

Comment (mcvayc) [reply src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java]: Yeah, I was worried about the same thing but Gemini assured me that: 

> No, XML cannot have a pound sign (whether referring to the British Pound symbol £ or the hash symbol #) in a tag or attribute name, as it is an illegal character according to the XML naming rules.

Comment (mcvayc) [reply src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java]: I'll see if I can find a more authoritative source

Comment (mcvayc) [reply src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java]: According to the [w3.org](https://www.w3.org/TR/xml/#NT-NameStartChar), xml names must start with one of these characters:

```
[4]   	NameStartChar	   ::=   	":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
[4a]   	NameChar	   ::=   	NameStartChar | "-" | "." | [0-9] | #xB7 | [#x0300-#x036F] | [#x203F-#x2040]
```

Comment (cowtowncoder) [reply src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java]: Having written 2 XML parsers, I concur. :)

(was thinking of using `&` but `#` is fine choice as well).

File: src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java (hunk 1 above)
Comment (mcvayc) [reply src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java]: I added a proposed improvement in the latest commit.  This is safer but less performant, since we copy the array even if there is no need.  Another option would be to only copy the array after we identify the first rename, but then we need to check if the array is not null each time that we rename.

File: src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java (hunk 5 above)
Comment (mcvayc) [reply src/main/java/tools/jackson/dataformat/xml/JacksonXmlAnnotationIntrospector.java]: I update the magic value to start with `&`.

**Review by cowtowncoder — APPROVED** [review]
LGTM!

**Comment by mcvayc** [comment]
> LGTM!

Thank you!  I found one more optimization I'd like to push.

**Comment by cowtowncoder** [comment]
@mcvayc This looks very good -- thank you for contributing it! I'll add release notes and merge it for inclusion in 3.2.0!

**Comment by cowtowncoder** [comment]
> > LGTM!
> 
> Thank you! I found one more optimization I'd like to push.

Ok I'll wait after updating release notes.

**Comment by mcvayc** [comment]
> > > LGTM!
> > 
> > 
> > Thank you! I found one more optimization I'd like to push.
> 
> Ok I'll wait after updating release notes.

Never mind, you beat me to it with your streamlining commit. :-)

I was going to delay the array copy.

File: src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java (hunk 1 above)
Comment (cowtowncoder) [reply src/main/java/tools/jackson/dataformat/xml/deser/XmlValueInstantiators.java]: I think this is acceptable: this does not occur for every read but only when deserializer is constructed.

**Comment by cowtowncoder** [comment]
@mcvayc Ok; good to, will merge. Looks like #306 is still partially failing, but fixing 5 issues is a pretty big achievement!

**Comment by cowtowncoder** [comment]
> @mcvayc Ok; good to, will merge. Looks like #306 is still partially failing, but fixing 5 issues is a pretty big achievement!

I am working on #306 -- test is buggy.

**Comment by mcvayc** [comment]
> > @mcvayc Ok; good to, will merge. Looks like #306 is still partially failing, but fixing 5 issues is a pretty big achievement!
> 
> I am working on #306 -- test is buggy.

Makes sense.  

Thanks for all that you do for the Jackson projects and for being so supportive of contributions.

**Comment by cowtowncoder** [comment]
> 
> Thanks for all that you do for the Jackson projects and for being so supportive of contributions.

Thank you for the kind words. It is good to get feedback like this.

And thank you for providing the fixes here!
